# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chanhui Lee
title: AI Master's Student
email: chlessling@gmail.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  chless
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Greeting. I'm Chanhui Lee, a master's student at UNIST, being supervised prof. Sungbin Lim. I'm interested with research areas like Deep Reinforcement Learning, neural processes, 3D face reconstruction.



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Neural Bootstrapping Neural Processes
        link: https://github.com/UNIST-LIM-Lab/NBS-NP
        # link_text: Project Website
        additional_links:
          - title:
            icon:
            url:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >

        description: | # this will include new lines to allow paragraphs


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LIM Lab, UNIST
        link: https://github.com/UNIST-LIM-Lab
        # link_text: boringcompany.com
        sub_title: Master's student
        caption: 2021 - Present
        quote: >

        description: | # this will include new lines to allow paragraphs


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNIST
        caption: 2014 - 2018
        sub_title: Chemical Engineering
        quote: >
          Ulsan National Institute of Science and Technology
        description: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
